import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#424654",
        "primary": "#0040a1",
        "tertiary-fixed-dim": "#ffb59b",
        "outline-variant": "#c3c6d6",
        "on-tertiary-fixed-variant": "#812800",
        "on-secondary-container": "#3e5181",
        "on-secondary-fixed": "#001847",
        "secondary-container": "#b3c5fd",
        "secondary": "#4a5d8e",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed": "#dae2ff",
        "outline": "#737785",
        "on-tertiary-container": "#ffcebd",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d9d9e4",
        "error-container": "#ffdad6",
        "inverse-primary": "#b2c5ff",
        "primary-container": "#0056d2",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f0fb",
        "surface": "#faf8ff",
        "primary-fixed": "#dae2ff",
        "on-tertiary-fixed": "#380d00",
        "surface-container": "#ededf8",
        "background": "#faf8ff",
        "surface-container-high": "#e7e7f2",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdbcf",
        "surface-container-low": "#f2f3fe",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed-variant": "#0040a1",
        "tertiary-container": "#a93802",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e1e2ec",
        "on-surface": "#191b23",
        "surface-tint": "#0056d2",
        "surface-bright": "#faf8ff",
        "on-primary-container": "#ccd8ff",
        "inverse-surface": "#2e3038",
        "on-primary-fixed": "#001847",
        "surface-variant": "#e1e2ec",
        "on-background": "#191b23",
        "tertiary": "#822800",
        "on-secondary-fixed-variant": "#324575",
        "secondary-fixed-dim": "#b3c5fd"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
export default config